// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_landing_layout from './routes/(landing)/_layout.tsx'
import * as $_landing_index from './routes/(landing)/index.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $api_joke from './routes/api/joke.ts'
import * as $api_v0_traffic_jam_index from './routes/api/v0/traffic-jam/index.ts'
import * as $greet_name_ from './routes/greet/[name].tsx'
import * as $counter from './islands/counter.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
	routes: {
		'./routes/(landing)/_layout.tsx': $_landing_layout,
		'./routes/(landing)/index.tsx': $_landing_index,
		'./routes/_app.tsx': $_app,
		'./routes/_middleware.ts': $_middleware,
		'./routes/api/joke.ts': $api_joke,
		'./routes/api/v0/traffic-jam/index.ts': $api_v0_traffic_jam_index,
		'./routes/greet/[name].tsx': $greet_name_,
	},
	islands: {
		'./islands/counter.tsx': $counter,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
